export const BREAKPOINT = 640;

export const THEME_COLOR = {
  VIOLET: "#A6B1E1",
  LIGHT_VIOLET: "#DCD6F7",
  LIGHTER_VIOLET: "#F4EEFF",
  DARK_VIOLET: "#424874",
  GRAY: "#F1F1F1",
  GRAYER: "#EDEDED",
};
